# Generated by Django 5.1.3 on 2025-02-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bread',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='breads/'),
        ),
        migrations.AddField(
            model_name='bread',
            name='ingredients',
            field=models.TextField(blank=True),
        ),
    ]
